import Head from 'next/head'
import styles from '../styles/Home.module.css'
import cx from 'classnames';
import { useEffect, useState } from 'react';
import { saveAs } from 'file-saver'; export default function Home() {

    const getSymbol = async (search) => {
        const res = await fetch(`/api/searchStockSymbol?search=${search}`);
        const data = await res.json();
        return data;
    }

    const storeData = async (symbol) => {
        const res = await fetch(`/api/getStockData?symbol=${symbol}`);
        const data = await res.json();
        const blob = new Blob([data], { type: "text/csv;charset=utf-8" });
        saveAs(blob, `${symbol}.json`);
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>STONKS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={cx(styles["form-signin"], "text-center", "mt-5")}>

                <form
                    onSubmit={async (e) => {
                        e.preventDefault();
                        if (!e.target[0].value) return alert("Please enter a company name");
                        alert("Saving Stock Data...")
                        const symbol = await getSymbol(e.target[0].value);
                        e.target.reset();
                        await storeData(symbol);
                        console.log(symbol);
                    }}
                >
                    <h1 className="h1 mb-3 fw-normal text-light">STONKS</h1>

                    <div className="form-floating mb-3">
                        <textarea type="text" className="form-control" id="Input" placeholder="Enter Text" autoComplete='false' />
                        <label htmlFor="Input">Enter Company&apos;s Name</label>
                    </div>
                    <button className={cx(styles["button"], "w-50", "btn", "btn-lg", "btn-outline-light")} type="submit">Submit</button>
                </form>
            </div>
        </div>
    )
}